name: Build YouTube Downloader

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # 允许手动触发

jobs:
  build-macos:
    runs-on: macos-13 # Intel Mac 运行器

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # 使用稳定版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Download yt-dlp
        run: |
          curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos -o yt-dlp
          chmod +x yt-dlp

      - name: Download ffmpeg
        run: |
          curl -L https://evermeet.cx/ffmpeg/ffmpeg-6.1.zip -o ffmpeg.zip
          unzip ffmpeg.zip
          chmod +x ffmpeg
          rm ffmpeg.zip

      - name: Verify downloads
        run: |
          echo "yt-dlp info:"
          file yt-dlp
          echo "ffmpeg info:"
          file ffmpeg

      - name: Build application
        run: |
          python build.py

      - name: Create release info
        run: |
          echo "构建信息:" > build-info.txt
          echo "构建时间: $(date)" >> build-info.txt
          echo "Python版本: $(python --version)" >> build-info.txt
          echo "系统信息: $(uname -a)" >> build-info.txt
          echo "架构信息:" >> build-info.txt
          file dist/YouTube下载器 >> build-info.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yt-downloader-macos-intel
          path: |
            dist/yt-downloader.app
            build-info.txt
          retention-days: 30
